### ISSUE TITLE
Embedded Stack was not created successfully

### ISSUE THREAD

**Issue by reckinam** [dougmoscrop/serverless-plugin-split-stacks#120]
When i trying to deploy serverless ,getting error embedded stack was not created successfully.
Below is the code format

```
`plugins:
  - serverless-plugin-split-stacks

custom:
  splitStacks:
    nestedStackCount: 20 # Controls the number of created nested stacks
    perFunction: false
    perType: false
    perGroupFunction: true`
```

How to solve this error ?
