### ISSUE TITLE
Plugin doesn't do anything

### ISSUE THREAD

**Issue by bart** [dougmoscrop/serverless-plugin-split-stacks#137]
Hey everyone, I have a deployed stack of more than 130 resources and would like to split it up using this plugin. But installing and adding it doesn't do anything. I don't get any notification or so about the plugin so looks like it's not getting loaded to me.

Here are some parts of my serverless.yml:
```
frameworkVersion: '2'
package:
  exclude:
    - secrets.yml
    - node_modules/**/.cache/**
    - layer/**

plugins:
  - serverless-layers
  - serverless-plugin-split-stacks
  - serverless-plugin-typescript
  - serverless-offline

custom:
  secrets: ${file(secrets.yml):${self:provider.stage}, file(secrets.yml):default}
  splitStacks:
    perFunction: true
    perType: false
```

Any idea how I can figure out why this plugin doesn't get loaded? I do my deployment with `AWS_PROFILE=<project> sls deploy` Might this be the problem? Thanks a lot!
