### ISSUE TITLE
Support encryption on custom deployment buckets

### ISSUE THREAD

**Issue by peterjcaulfield** [dougmoscrop/serverless-plugin-split-stacks#16]
This plugin doesn't seem to support encryption of a custom serverless deployment bucket. 

Given the following extract from a serverless config:

```
provider:
  name: aws
  runtime: nodejs6.10
  deploymentBucket:
    name: myAmazingDeploymentBucket
    serverSideEncryption: AES256
```

I would expect *all* put's to be encrypted. What actually happens is the deployment zip file and the `compiled-cloudformation-template.json` is encrypted but the nested stack files generated are not.

In my case I got `cloudformation-template-Permissions-nested-stack.json` and `cloudformation-template-API-nested-stack.json` files pushed up to the deployment bucket unencrypted.
