### ISSUE TITLE
Readme instructions

### ISSUE THREAD

**Issue by eduard93** [dougmoscrop/serverless-plugin-split-stacks#198]
I have a deployed stack with 500 resources. After adding a few more I wanted to use `serverless-plugin-split-stacks` as I get `The CloudFormation template is invalid: Template format error: Number of resources, 507, is greater than maximum allowed, 500` error.

I installed the plugin and added this as a first thing in a custom section:

```yaml
custom:
  splitStacks:
    perFunction: false
    perType: true
    perGroupFunction: false
```

alternatively tried: 

```yaml
custom:
  splitStacks:
    perFunction: true
    perType: false
    perGroupFunction: false
```

But the error I get is still: `The CloudFormation template is invalid: Template format error: Number of resources, 507, is greater than maximum allowed, 500`.

Is there some step I'm missing?
