### ISSUE TITLE
Does this plugin supports serverless v3 and node v16?

### ISSUE THREAD

**Issue by kannan007** [dougmoscrop/serverless-plugin-split-stacks#203]
Am trying to use this plugin, but it doesn't split any of my stacks so am having hard time to figure it out whether the mistake is from my side or the plugin doesn't support. am attaching my sample

```
splitStacks:
    nestedStackCount: 20
    perFunction: false
    perType: false
    perGroupFunction: false
    force: true
```

any help will be appreciated
