### ISSUE TITLE
APINestedStack Error

### ISSUE THREAD

**Issue by yogumanivannan** [dougmoscrop/serverless-plugin-split-stacks#21]
An error occurred: APINestedStack - Template format error: Outputs count 62 is greater than max allowed 60.

I get this issue while using serverless deploy

**Comment by dougmoscrop** [comment]
Yeah, this is another CloudFormation limit that this plugin does not have logic for trying to solve. It's basically a case of having to further divide in to even *more* nested stacks because of output/input limit, not just resource count. I can imagine how we might accomplish it, just not done.

**Comment by yogumanivannan** [comment]
oops i was really hoping to have a solution... Is there any other alternatives left or should i architect my endpoints in a way that it doesn't affect resource count or size limit ?

**Comment by dougmoscrop** [comment]
Do you have a lot of separate functions/endpoints? An alternative is to combine them together, and just have one, or maybe a few.

```yaml

functions:
  api:
    handler: api.js
    events:
      - http ANY /
      - http ANY /{any+}
```

or per some kind of logical thing

```yaml

functions:
  fooApi:
    handler: api.js
    events:
      - http ANY /foo
      - http ANY /foo/{any+}

functions:
  fooApi:
    handler: api.js
    events:
      - http ANY /bar
      - http ANY /bar/{any+}
```

But not "getFoo", "putFoo", "postFoo", etc.

You can see my module https://github.com/dougmoscrop/serverless-http which will let you use routing like Koa/Express to make the function handler code dead simple
