### ISSUE TITLE
serverless-split-stack plugin with provisionalConcurrency confguration making deployment failure

### ISSUE THREAD

**Issue by skysoft999** [dougmoscrop/serverless-plugin-split-stacks#212]
serverless-split-stack plugin with provisionalConcurrency configuration making deployment failure.

getting error:

Environment: darwin, node 14.15.4, framework 3.34.0 (local) 3.34.0v (global), plugin 6.2.3, SDK 4.3.2
Error:
The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [AuthorizerFuncLambdaFunctionArnParameter] in the Resources block of the template

```
  splitStacks:
    nestedStackCount: 30 # Controls the number of created nested stacks
    perFunction: true
    # perType: false
    # stackConcurrency: 10
    # resourceConcurrency: 10



```
