### ISSUE TITLE
Circular dependency between resources: potential issue with `resourceConcurrency` and `stackConcurrency` 

### ISSUE THREAD

**Issue by turakvlad** [dougmoscrop/serverless-plugin-split-stacks#215]
We have the same issue as described in https://github.com/dougmoscrop/serverless-plugin-split-stacks/issues/122 and https://github.com/dougmoscrop/serverless-plugin-split-stacks/issues/188. The latest issue has been closed. That's why I decided to create a new issue.

Having `resourceConcurrency` set, does not allow us to deploy the stack for the first time. On the other hand, `stackConcurrency` works for the first deployment but does not work for subsequent ones. To better show these issues, please take a look at the cases below.

The config below is not working if we want to deploy the stack for the first time:

```
  splitStacks:
    perFunction: true
    perType: false
    perGroupFunction: false
    stackConcurrency: 5
    resourceConcurrency: 10
```

We have this error:

```
The CloudFormation template is invalid: Circular dependency between resources: [AssignRoleNestedStack, DisconnectIdpNestedStack, GetCredentialsUsageNestedStack, UpdateEmailTemplateNestedStack, ...]
```

Removing `resourceConcurrency` from the config above makes deploying the stack for the first time possible. 

However, the below config is not working for subsequent deployments.

```
  splitStacks:
    perFunction: true
    perType: false
    perGroupFunction: false
    stackConcurrency: 5
```

We have the same error as above:

```
The CloudFormation template is invalid: Circular dependency between resources: [UpdateEmailTemplateNestedStack, CustomMessageNestedStack, SetDefaultEmailTemplateNestedStack, UpdateGroupNestedStack, ...].
```

It looks like `resourceConcurrency` creates some circular dependencies between resources and `stackConcurrency` does the same but between nested stacks. 

Is there any way to handle this issue? Currently, we removed both options and left only:

```
  splitStacks:
    perFunction: true
    perType: false
    perGroupFunction: false
```

However, I am afraid that we will hit API rate limit errors in the nearest feature and the problem will arise again.

Thank you for any tips in advance! 🙏
