### ISSUE TITLE
Can't Specify Custom Deployment Bucket

### ISSUE THREAD

**Issue by brettneese** [dougmoscrop/serverless-plugin-split-stacks#6]
When I specify a custom deployment bucket in `provider.deploymentBucket`; ie:

```
provider:
  deploymentBucket:
    name: $bucket
    serverSideEncryption: AES256 
```

I get:

```
The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [ServerlessDeploymentBucket] in the Resources block of the template
```

The easiest solution to this problem is to simply remove the `provider.deploymentBucket` property and use whatever the Serverless framework gives you, however, it would be nice if this plugin did not have this issue.

That being said, I don't understand any of the magic going on here, so that solution is good enough for us for now.
