### ISSUE TITLE
sls package requiring AWS credentials

### ISSUE THREAD

**Issue by davecarlson** [dougmoscrop/serverless-plugin-split-stacks#69]
In our workflow, `sls package` is run separately to the deploy step.

When adding in this plugin, I am receiving the following error when doing `sls package`:

``` Serverless Error ---------------------------------------
 
  AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://bit.ly/aws-creds-setup>.
```

I cannot see anything that calls that that AWS cli access is required in the README, and wouldn't normally expect it to be needed for packaging. Is this by design, or is it doing something that requires AWS access?

serverless.yml:
```
plugins:
  - serverless-webpack
  - serverless-plugin-split-stacks  
  - serverless-dynamodb-local
  - serverless-offline

custom: 
  splitStacks:
    perFunction: false
    perType: true

```
