### ISSUE TITLE
Ref in serverless iamRoleStatements gets parameterized

### ISSUE THREAD

**Issue by HumbleBeck** [dougmoscrop/serverless-plugin-split-stacks#95]
Hi everyone,
I have this line 
```
iamRoleStatements:
    - Effect: Allow
      Action: secretsmanager:GetSecretValue
      Resource:
         Ref: ApiKeySecret
```
and custom resource 
```
Resources:
  ApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      GenerateSecretString: 
        ExcludePunctuation: true
        GenerateStringKey: SIGNATURE_KEY
        IncludeSpace: false
        PasswordLength: 32
        SecretStringTemplate: "{}"
      Name: ${{self:service.name}}-${{self:provider.stage}}-secrets

```
even those 2 resources in same(root) stack, role policy has
```
{
  "Effect": "Allow",
  "Action": "secretsmanager:GetSecretValue",
  "Resource": {
    "Ref": "ApiKeySecretParameter"
  }
},
```
Instead of 
```
{
  "Effect": "Allow",
  "Action": "secretsmanager:GetSecretValue",
  "Resource": {
    "Ref": "ApiKeySecret"
  }
},
```
I have to say that this plugin was enabled only when main stack reached 200 limit.
